### ISSUE TITLE
Global Chat Users is unaccessible.

### ISSUE THREAD

**Issue by deepak1725** [pubnub/chat-engine#266]
Tried to Assess via 
```
 this.ChatEngine = ChatEngineCore.create({
            publishKey: environment.PUBNUB_PUB_KEY,
            subscribeKey: environment.PUBNUB_SUB_KEY,
        });
let user = this.ChatEngine.global.users[0];
        console.log('User', user);
//Undefined
```
Each time i tried to access users, it returned `undefined`

**Comment by ianjennings** [comment]
You never called ```ChatEngine.connect()```

**Comment by deepak1725** [comment]
@ianjennings 
Please see this:
```
let users = this.ChatEngine.global.users
console.log('AllUser', users);
console.log("All Users in Array", Object.keys(user));
console.log("First User", user[0]);
```
O/P:
![online](https://user-images.githubusercontent.com/21026016/34142397-e7fe5076-e4ac-11e7-8e1b-75ee18504eba.png)

**Comment by ianjennings** [comment]
```user``` is undefined in your code example above.

```chat.users``` is an object and not an array.

**Comment by deepak1725** [comment]
My Bad..Sorry!! 
what i meant actually was:
```
let users = this.ChatEngine.global.users
console.log('AllUser', users);
console.log("All Users in Array", Object.keys(users));
console.log("Single User", user.kapil);
```
The results still same...
![global_users](https://user-images.githubusercontent.com/21026016/34192492-4d8eaf5e-e574-11e7-9a13-73339721419d.png)

I tried with Promise resolve, but still No Luck..

Please note same is the issue with `this.ChatEngine.chats`

**Comment by deepak1725** [comment]
there is little icon `i` in console which says : `Value below was evaluated just now` which means its an asynchronous call and values are calculated at runtime..
so followed below thread for resolution: 
https://stackoverflow.com/questions/23429203/weird-behavior-with-objects-console-log

but it gives up circular dependency error..

**Comment by ianjennings** [comment]
Oh, there's a bug in chat.users. Chats are not currently always correctly populated with users in the channel. This will be fixed in the next release.

ChatEngine.users for now.

```js
ChatEngine
RootEmitter {events: {…}, name: "RootEmitter", emitter: EventEmitter, _emit: ƒ, _on: ƒ, …}
ChatEngine.users
{user-1513788493644: Me, user-1513788439824: User}
Object.keys(ChatEngine.users)
(2) ["user-1513788493644", "user-1513788439824"]
ChatEngine.users['user-1513788493644']
Me {events: {…}, name: "Me", emitter: EventEmitter, _emit: ƒ, _on: ƒ, …}
ChatEngine.users['user-1513788439824']
User {events: {…}, name: "User", emitter: EventEmitter, _emit: ƒ, _on: ƒ, …}
```

You can also find users online by doing ```chat.on('$.online')```.

**Comment by ianjennings** [comment]
This is related to #260

**Comment by ianjennings** [comment]
#271 states that me.session.chats is not properly reflecting the map of chats after a leave event is emitted.

**Comment by ianjennings** [comment]
Working on this in #297. Should be fixed there.

**Comment by deepak1725** [comment]
@ianjennings I Still not able to see any data in `chat.users`

In ref to https://www.pubnub.com/docs/chat-engine/online-list 
What i trying to achieve is getting list of online users of a chat from ChatObj


What i tried:
```
let chat = this.ChatEngine.Chat("Testing");
console.log(chat.users)  
This gives empty results.

![issue](https://user-images.githubusercontent.com/21026016/36938644-9e72c814-1f4a-11e8-9f98-29e529eafe7a.jpg)



```
